#!/usr/bin/env bash

set -e

[[ ! -z "$SUDO_USER" ]] && user=$SUDO_USER || user=$LOGNAME

DATA_PATH=${1:-/opt/cathook/data}

if [ "$EUID" != 0 ]; then
    exec sudo "$0" "$@"
fi

if ! [ -d "$DATA_PATH" ]; then
    echo "Creating cathook data directory at $DATA_PATH"
    mkdir -p "$DATA_PATH"
    chown -R "$user" "$DATA_PATH"
    chmod -R 774 "$DATA_PATH"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

echo "Installing cathook data to $DATA_PATH"
if command -v rsync >/dev/null 2>&1; then
    rsync -avh "$SCRIPT_DIR/data/" "$DATA_PATH"
    rsync -avh --ignore-existing "$SCRIPT_DIR/config_data/" "$DATA_PATH"
else
    cp -r "$SCRIPT_DIR/data/"* "$DATA_PATH/"
    cp -rn "$SCRIPT_DIR/config_data/"* "$DATA_PATH/"
fi
chown -R "$user" "$DATA_PATH"
chmod -R 777 "$DATA_PATH"
echo "Data installation complete: $DATA_PATH"
